[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
lib_ldf_mode = chain
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -I include
lib_deps =
  lvgl/lvgl@8.3.11
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.5
